### ISSUE TITLE
WSL2 のインストール方法GA

### ISSUE THREAD

**Issue by yamamotojapan** [TakanoTaiga/install-ros2-on-WSL2#1]
WSL2のインストール方法が古いものになってると思います

↓現在のドキュメント
[WSL のインストール | Microsoft Docs](https://docs.microsoft.com/ja-jp/windows/wsl/install)

**Comment by TakanoTaiga** [comment]
このドキュメントの方法であまり上手く行かなかった記憶があるのですが(あやふや)、実行しましたでしょうか？今からこちらでも実行し、確認します。

**Comment by TakanoTaiga** [comment]
古いものになってました。修正いたします。
