### ISSUE TITLE
bashrcを参照している場所が違うと思います

### ISSUE THREAD

**Issue by yamamotojapan** [TakanoTaiga/install-ros2-on-WSL2#2]
https://github.com/TakanoTaiga/install-ros2-on-WSL2/blob/da75751e3b475f00565fa98c022674431e312003/README.md?plain=1#L75

ここが

```sh
vim ~/.bashrc
```
だと思います。

**Comment by TakanoTaiga** [comment]
ご指摘ありがとうございます。修正しておきます。
